source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'slideout' do
	pod 'Alamofire', '~> 4.4'
	pod 'EasyToast', '~> 2.0'
	pod 'SwiftSpinner'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare'
end
